// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fontsvmexlkwqgbfrwtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvbnRzdm1leGxrd3FnYmZyd3RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMDk5MjQsImV4cCI6MjA3NDc4NTkyNH0.BJp257he7xMmNLFE6LPMrTHiDJHYjoIJtbCnf2sfZJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});